// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
//		如存在本生成代码外的新需求，请在相同命名空间下创建同名分部类实现 UserDataConfigurationAppend 分部方法。
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using FluentJson.Configuration;
using FluentJson;
using XIMALAYA.PCDesktop.Core.Data.Decorator;
using XIMALAYA.PCDesktop.Core.Models.User;

namespace XIMALAYA.PCDesktop.Core.Data
{
    /// <summary>
    ///     UserData
    /// </summary>
    /// <typeparam name="T"></typeparam>
    public partial class UserDataDecorator<T> : Decorator<T>
    {
        partial void doAddOtherConfig();
        /// <summary>
        ///     
        /// </summary>
        /// <typeparam name="result"></typeparam>
        public UserDataDecorator(Result<T> result)
            : base(result)
        {

        }
        /// <summary>
        ///     
        /// </summary>
        /// <typeparam name="result"></typeparam>
        public override void doAddConfig()
        {
            base.doAddConfig();
            this.Config.MapType<UserData>(map => map
                                    .Field<System.Boolean>(field => field.IsVerified, type => type.To("isVerified"))
                    .Field<System.String>(field => field.LargeLogo, type => type.To("largeLogo"))
                    .Field<System.String>(field => field.NickName, type => type.To("nickname"))
                    .Field<System.String>(field => field.PersonDescribe, type => type.To("personDescribe"))
            );
        }
    }
}
