// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
//		如存在本生成代码外的新需求，请在相同命名空间下创建同名分部类实现 SuperExploreIndexConfigurationAppend 分部方法。
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using FluentJson.Configuration;
using FluentJson;
using XIMALAYA.PCDesktop.Core.Models;
using XIMALAYA.PCDesktop.Core.Models.Discover;
using XIMALAYA.PCDesktop.Core.Models.Category;
using XIMALAYA.PCDesktop.Core.Models.FocusImage;
using XIMALAYA.PCDesktop.Core.Models.Recommend;
using XIMALAYA.PCDesktop.Core.Models.Subject;

namespace XIMALAYA.PCDesktop.Core.Data
{
    partial class SuperExploreIndexResultConfig<T> : IJsonConfig
           where T : SuperExploreIndexResult
    {

        /// <summary>
        /// 添加配置
        /// </summary>
        partial void AppendConfig()
        {
            this.Config.MapType<T>(map => map.AllFields()
                .Field<int>(field => field.Ret, ret => ret
                    .To("ret")
                ).Field<CategoryListResult>(field => field.Categories, f => f
                    .To("categories")
                ).Field<FocusImageResult>(field => field.FocusImages, f => f
                    .To("focusImages")
                ).Field<RecommendAlbumResult>(field => field.RecommendAlbums, f => f
                    .To("recommendAlbums")
                ).Field<SubjectListResult>(field => field.Subjects, f => f
                    .To("subjects")
                )
                //.Field<SubjectListResult>(field => field.Subjects, f => f
                //    .To("subjects")
                //)
            );
        }

    }
}
